using System.Collections.Generic;
using System.Linq;
using System.Text;
using MetalRenderingEngine.ShaderGen.Models;

namespace MetalRenderingEngine.ShaderGen.Emit;

/// <summary>
/// 生成类型安全的 C# Binding 类。
/// 每个 [Shader] struct 生成一个 {StructName}Binding 类，提供强类型资源 Setter 和 Dispatch/Draw 入口。
/// </summary>
internal static class BindingClassEmitter
{
    /// <summary>生成 Binding 类源码。</summary>
    public static string GenerateBinding(ShaderInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by MetalRenderingEngine.ShaderGen from {info.StructName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine($"namespace {info.Namespace};");

        sb.AppendLine();
        sb.AppendLine("using MetalRenderingEngine.Metal;");
        sb.AppendLine("using MetalRenderingEngine.Metal.Interop;");
        sb.AppendLine();

        // 计算资源槽位
        var resourceSlots = ComputeResourceSlots(info);
        var bufferFields = info.Fields
            .Where(f => f.Kind is ResourceKind.ReadWriteBuffer or ResourceKind.ReadOnlyBuffer)
            .ToList();
        var cbFields = info.Fields
            .Where(f => f.Kind is ResourceKind.ConstantBuffer)
            .ToList();

        sb.AppendLine($"internal sealed class {info.StructName}Binding : System.IDisposable");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly MetalRenderingEngine.Metal.MetalComputePipelineState _pipeline;");
        sb.AppendLine();

        // Buffer 字段缓存
        foreach (var field in bufferFields)
        {
            sb.AppendLine($"    private MetalRenderingEngine.Metal.MetalBuffer? _{field.Name};");
        }

        // CB 数据缓存（标量合并到 ContantBuffer）
        if (cbFields.Count > 0)
        {
            sb.AppendLine();
            foreach (var field in cbFields)
            {
                sb.AppendLine($"    private MetalRenderingEngine.Metal.MetalBuffer? _{field.Name}_buffer;");
            }
        }

        sb.AppendLine();
        // 构造函数
        sb.AppendLine($"    public {info.StructName}Binding(");
        sb.AppendLine($"        MetalRenderingEngine.Metal.MetalDevice device,");
        sb.AppendLine($"        MetalRenderingEngine.Metal.MetalFunction function)");
        sb.AppendLine("    {");
        sb.AppendLine("        _pipeline = device.NewComputePipelineState(function);");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    public MetalRenderingEngine.Metal.MetalComputePipelineState Pipeline => _pipeline;");

        // Setter 方法：每个 buffer 资源
        foreach (var field in bufferFields)
        {
            sb.AppendLine();
            if (resourceSlots.TryGetValue(field.Name, out var slot))
            {
                sb.AppendLine($"    /// <summary>设置资源 {field.Name}（slot {slot}）。</summary>");
                sb.AppendLine($"    public void Set{field.Name}(MetalRenderingEngine.Metal.MetalBuffer buffer)");
                sb.AppendLine("    {");
                sb.AppendLine($"        _{field.Name} = buffer;");
                sb.AppendLine("    }");
            }
        }

        // Compute Dispatch 方法
        if (info.Kind == ShaderKind.Compute)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>派发计算任务。</summary>");
            sb.AppendLine("    public void Dispatch(");
            sb.AppendLine("        MetalRenderingEngine.Metal.MetalCommandBuffer cmdBuffer,");
            sb.AppendLine("        int threadgroupsX, int threadgroupsY, int threadgroupsZ)");
            sb.AppendLine("    {");
            sb.AppendLine("        using var encoder = cmdBuffer.ComputeCommandEncoder();");
            sb.AppendLine("        encoder.SetComputePipelineState(_pipeline);");
            sb.AppendLine();

            // 绑定 buffer 资源（按槽位顺序）
            var orderedFields = bufferFields
                .Select(f => (Field: f, Slot: resourceSlots.TryGetValue(f.Name, out var s) ? s : -1))
                .Where(x => x.Slot >= 0)
                .OrderBy(x => x.Slot);
            foreach (var (field, slot) in orderedFields)
            {
                sb.AppendLine($"        if (_{field.Name} is not null)");
                sb.AppendLine($"            encoder.SetBuffer(_{field.Name}!, 0, {slot});");
            }

            // CB 绑定
            if (cbFields.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        // ConstantBuffer 绑定（需先创建并上传数据到 MetalBuffer）");
                foreach (var field in cbFields)
                {
                    var slot = resourceSlots.TryGetValue(field.Name, out var s) ? s : 0;
                    sb.AppendLine($"        if (_{field.Name}_buffer is not null)");
                    sb.AppendLine($"            encoder.SetBuffer(_{field.Name}_buffer!, 0, {slot});");
                }
            }

            // 标量字段的 Implicit ConstantBuffer（b0）
            var scalarFields = info.Fields.Where(f => f.Kind == ResourceKind.Scalar).ToList();
            if (scalarFields.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        // 标量常量通过 SetBytes 绑定到 b0（由 Slang 输出中的 _constants 隐式 ConstantBuffer 使用）");
                sb.AppendLine("        // TODO: 自动将所有标量字段打包为 struct 并上传");
            }

            sb.AppendLine();
            sb.AppendLine($"        encoder.DispatchThreadgroups(");
            sb.AppendLine($"            new WMTSize((ulong)threadgroupsX, (ulong)threadgroupsY, (ulong)threadgroupsZ),");
            sb.AppendLine($"            new WMTSize({info.ThreadGroupX}, {info.ThreadGroupY}, {info.ThreadGroupZ}));");
            sb.AppendLine("    }");
        }

        // Dispose
        sb.AppendLine();
        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");
        sb.AppendLine("        _pipeline?.Dispose();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>计算每个字段的分配槽位（与 BindingLayoutEmitter 逻辑一致）。</summary>
    private static Dictionary<string, int> ComputeResourceSlots(ShaderInfo info)
    {
        var slots = new Dictionary<string, int>();
        int nextU = 0, nextT = 0, nextS = 0, nextB = 0;

        foreach (var field in info.Fields)
        {
            int slot = field.Kind switch
            {
                ResourceKind.ReadWriteBuffer => nextU++,
                ResourceKind.ReadOnlyBuffer => nextT++,
                ResourceKind.Texture2D => nextT++,
                ResourceKind.SamplerState => nextS++,
                ResourceKind.ConstantBuffer => nextB++,
                _ => -1,
            };
            if (slot >= 0)
                slots[field.Name] = slot;
        }
        return slots;
    }
}
