using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using MetalRenderingEngine.ShaderGen.Models;
using MetalRenderingEngine.ShaderGen.Translation;

namespace MetalRenderingEngine.ShaderGen.Emit;

/// <summary>
/// Slang 代码生成主逻辑。
/// 从 ShaderInfo 中间模型生成完整的 Slang 着色器源码。
/// </summary>
internal static class SlangEmitter
{
    /// <summary>
    /// 生成完整 Slang 源码。
    /// </summary>
    /// <param name="info">着色器中间模型。</param>
    /// <param name="diagnostics">输出：翻译过程中遇到的诊断。</param>
    /// <returns>Slang 源码，若生成失败返回 null。</returns>
    public static string? Emit(ShaderInfo info, out ImmutableArray<Diagnostic> diagnostics)
    {
        var diagList = new List<Diagnostic>();
        try
        {
            var writer = new SlangWriter();
            WriteHeader(writer, info);

            // 资源分配
            var layout = new BindingLayoutEmitter();
            WriteResourceDeclarations(writer, info, layout);

            // 写入辅助函数
            WriteHelperMethods(writer, info, diagList);

            // 写入入口函数
            switch (info.Kind)
            {
                case ShaderKind.Compute:
                    WriteComputeEntry(writer, info, layout, diagList);
                    break;
                case ShaderKind.Vertex:
                    WriteVertexEntry(writer, info, layout, diagList);
                    break;
                case ShaderKind.Fragment:
                    WriteFragmentEntry(writer, info, layout, diagList);
                    break;
            }

            diagnostics = diagList.ToImmutableArray();
            return writer.ToString();
        }
        catch (TranslationException tex)
        {
            if (tex.SourceLocation is not null)
            {
                diagList.Add(Diagnostic.Create(
                    Diagnostics.ShaderDiagnostics.UnsupportedExpression,
                    tex.SourceLocation,
                    tex.Message));
            }
            diagnostics = diagList.ToImmutableArray();
            return null;
        }
    }

    // ─── 文件头 ──────────────────────────────────────────────

    private static void WriteHeader(SlangWriter w, ShaderInfo info)
    {
        w.WriteLine("// <auto-generated />");
        w.WriteLine($"// Generated by MetalRenderingEngine.ShaderGen from {info.StructName}");
        w.WriteLine();
    }

    // ─── 资源声明 ────────────────────────────────────────────

    private static void WriteResourceDeclarations(SlangWriter w, ShaderInfo info, BindingLayoutEmitter layout)
    {
        var scalarFields = new List<FieldInfo>();

        foreach (var field in info.Fields)
        {
            var slangType = GetSlangResourceType(field);
            layout.AddField(field, slangType);

            if (field.Kind == ResourceKind.Scalar)
            {
                scalarFields.Add(field);
            }
            else
            {
                // 直接声明资源
                if (layout.FieldSlots.TryGetValue(field.Name, out var slot))
                {
                    w.WriteLine($"{slangType} {field.Name} : register({slot.Register});");
                }
            }
        }

        // 标量字段合并为隐式 ConstantBuffer
        if (scalarFields.Count > 0)
        {
            w.WriteLine();
            w.WriteLine($"// ─── Scalar constants ───");
            var cbName = $"{info.StructName}_Constants";
            w.WriteLine($"struct {cbName}");
            using (w.BeginBlock())
            {
                foreach (var sf in scalarFields)
                {
                    var slangType = GetSlangScalarType(sf.TypeName);
                    w.WriteLine($"{slangType} {sf.Name};");
                }
            }

            // 标量字段统一在 b0
            w.WriteLine($"ConstantBuffer<{cbName}> _constants : register(b0);");
        }

        w.WriteLine();
    }

    // ─── 辅助函数 ────────────────────────────────────────────

    private static void WriteHelperMethods(SlangWriter w, ShaderInfo info, List<Diagnostic> diagList)
    {
        foreach (var method in info.HelperMethods)
        {
            // 翻译方法体中的语句
            var translator = new StatementTranslator(GetThreadIdMappings(info));
            var body = TryTranslateBody(method.Body, translator, diagList);

            w.WriteLine($"// {method.Name}");
            w.Write($"{method.ReturnType} {method.Name}(");

            for (int i = 0; i < method.Parameters.Count; i++)
            {
                if (i > 0) w.Write(", ");
                w.Write($"{method.Parameters[i].SlangType} {method.Parameters[i].Name}");
            }

            w.WriteLine(")");
            w.WriteLine(body);
            w.WriteLine();
        }
    }

    // ─── Compute 入口 ────────────────────────────────────────

    private static void WriteComputeEntry(SlangWriter w, ShaderInfo info, BindingLayoutEmitter layout, List<Diagnostic> diagList)
    {
        // [numthreads(X, Y, Z)]
        // [shader("compute")]
        w.WriteLine($"[numthreads({info.ThreadGroupX}, {info.ThreadGroupY}, {info.ThreadGroupZ})]");
        w.WriteLine(@"[shader(""compute"")]");
        w.Write("void main(");

        // 参数：dispatchThreadId : SV_DispatchThreadID
        var paramName = GetExecuteParameterName(info, 0, "id");
        w.Write($"uint3 {paramName} : SV_DispatchThreadID");

        w.WriteLine(")");

        // 翻译 Execute 方法体
        var translator = new StatementTranslator(GetThreadIdMappings(info));
        var body = TryTranslateBody(info.ExecuteMethodBody, translator, diagList);
        w.WriteLine(body);
    }

    /// <summary>从 Execute 方法获取参数名，优先使用实际参数名，其次从类型推导，最后用 fallback。</summary>
    private static string GetExecuteParameterName(ShaderInfo info, int index, string fallback)
    {
        if (info.ExecuteParameterNames.Count > index && !string.IsNullOrEmpty(info.ExecuteParameterNames[index]))
            return info.ExecuteParameterNames[index];
        if (info.ExecuteParameters.Count > index)
            return ExtractSimpleName(info.ExecuteParameters[index]);
        return fallback;
    }

    // ─── Vertex 入口 ────────────────────────────────────────

    private static void WriteVertexEntry(SlangWriter w, ShaderInfo info, BindingLayoutEmitter layout, List<Diagnostic> diagList)
    {
        // 分配语义
        AssignVertexInputSemantics(info.InputStructFields);
        AssignVertexOutputSemantics(info.OutputStructFields);

        var inputStructName = GetSimpleTypeName(info.InputTypeName);
        var outputStructName = GetSimpleTypeName(info.OutputTypeName);

        if (string.IsNullOrEmpty(inputStructName))
            inputStructName = $"{info.StructName}_Input";
        if (string.IsNullOrEmpty(outputStructName))
            outputStructName = $"{info.StructName}_Output";

        // 同一类型同时用于输入和输出时，用 _Input/_Output 后缀区分（不同语义）
        bool sameType = inputStructName == outputStructName;
        if (sameType)
        {
            WriteStructDeclaration(w, $"{inputStructName}_Input", info.InputStructFields);
            WriteStructDeclaration(w, $"{outputStructName}_Output", info.OutputStructFields);
            inputStructName = $"{inputStructName}_Input";
            outputStructName = $"{outputStructName}_Output";
        }
        else
        {
            WriteStructDeclaration(w, inputStructName, info.InputStructFields);
            WriteStructDeclaration(w, outputStructName, info.OutputStructFields);
        }

        // 获取参数名
        var paramName = GetExecuteParameterName(info, 0, "input");

        // 入口点
        w.WriteLine(@"[shader(""vertex"")]");
        w.Write($"{outputStructName} main({inputStructName} {paramName})");
        w.WriteLine();

        // 翻译 Execute 方法体
        var translator = new StatementTranslator(new Dictionary<string, string>()); // 无 ThreadId 映射
        var body = TryTranslateBody(info.ExecuteMethodBody, translator, diagList);
        w.WriteLine(body);
    }

    // ─── Fragment 入口 ────────────────────────────────────────

    private static void WriteFragmentEntry(SlangWriter w, ShaderInfo info, BindingLayoutEmitter layout, List<Diagnostic> diagList)
    {
        // 分配输入语义
        AssignFragmentInputSemantics(info.InputStructFields);

        var inputStructName = GetSimpleTypeName(info.InputTypeName);
        if (string.IsNullOrEmpty(inputStructName))
            inputStructName = $"{info.StructName}_Input";

        // 判断输出是否为简单类型（如 float4 → 直接 SV_Target）
        var isSimpleOutput = info.OutputTypeName is "float4"
            or "MetalRenderingEngine.Shader.float4"
            or "float" or "float3" or "float2"
            or "int" or "uint";

        var outputTypeStr = isSimpleOutput
            ? MapCSharpTypeToSlang(info.OutputTypeName)
            : GetSimpleTypeName(info.OutputTypeName);

        // 仅当有输入字段时才声明输入结构体
        if (info.InputStructFields.Count > 0)
        {
            WriteStructDeclaration(w, inputStructName, info.InputStructFields);
        }

        // 如果输出是 struct（非简单类型），声明输出结构体
        if (!isSimpleOutput && info.OutputStructFields.Count > 0)
        {
            AssignFragmentOutputSemantics(info.OutputStructFields);
            w.WriteLine($"struct {outputTypeStr}");
            using (w.BeginBlock())
            {
                foreach (var field in info.OutputStructFields)
                {
                    w.WriteLine($"{field.SlangType} {field.Name} : {field.Semantic};");
                }
            }
            w.WriteLine();
        }

        // 参数名
        var paramName = GetExecuteParameterName(info, 0, "input");

        // 入口点
        w.WriteLine(@"[shader(""fragment"")]");
        w.Write($"{outputTypeStr} main(");

        if (info.InputStructFields.Count > 0)
        {
            w.Write($"{inputStructName} {paramName}");
        }
        else
        {
            w.Write("void");
        }

        if (isSimpleOutput)
        {
            w.Write(") : SV_Target");
        }
        else
        {
            w.Write(")");
        }
        w.WriteLine();

        // 翻译 Execute 方法体
        var translator = new StatementTranslator(new Dictionary<string, string>());
        var body = TryTranslateBody(info.ExecuteMethodBody, translator, diagList);
        w.WriteLine(body);
    }

    // ─── 语义分配 ────────────────────────────────────────────

    /// <summary>根据字段名惯例分配顶点输入语义（POSITION/COLOR/NORMAL/TEXCOORD）。</summary>
    private static void AssignVertexInputSemantics(List<StructFieldInfo> fields)
    {
        int texCoordCounter = 0;
        foreach (var field in fields)
        {
            field.Semantic = field.Name switch
            {
                "Position" => "POSITION",
                "Color" => "COLOR",
                "Normal" => "NORMAL",
                "Tangent" => "TANGENT",
                "UV" or "TexCoord" => $"TEXCOORD{texCoordCounter++}",
                _ => $"TEXCOORD{texCoordCounter++}",
            };
        }
    }

    /// <summary>分配顶点输出语义（Position → SV_Position，其余 TEXCOORD）。</summary>
    private static void AssignVertexOutputSemantics(List<StructFieldInfo> fields)
    {
        int texCoordCounter = 0;
        foreach (var field in fields)
        {
            if (field.Name == "Position")
            {
                field.Semantic = "SV_Position";
                field.IsSystemValue = true;
            }
            else
            {
                field.Semantic = $"TEXCOORD{texCoordCounter++}";
            }
        }
    }

    /// <summary>分配片元输入语义（全部 TEXCOORD）。</summary>
    private static void AssignFragmentInputSemantics(List<StructFieldInfo> fields)
    {
        int texCoordCounter = 0;
        foreach (var field in fields)
        {
            field.Semantic = $"TEXCOORD{texCoordCounter++}";
        }
    }

    /// <summary>分配片元输出语义（SV_Target0, SV_Target1, ...）。</summary>
    private static void AssignFragmentOutputSemantics(List<StructFieldInfo> fields)
    {
        for (int i = 0; i < fields.Count; i++)
        {
            fields[i].Semantic = $"SV_Target{i}";
            fields[i].IsSystemValue = true;
        }
    }

    /// <summary>写入 Slang struct 声明，字段带语义绑定。</summary>
    private static void WriteStructDeclaration(SlangWriter w, string structName, List<StructFieldInfo> fields)
    {
        if (fields.Count == 0) return;

        w.WriteLine($"struct {structName}");
        using (w.BeginBlock())
        {
            foreach (var field in fields)
            {
                if (!string.IsNullOrEmpty(field.Semantic))
                    w.WriteLine($"{field.SlangType} {field.Name} : {field.Semantic};");
                else
                    w.WriteLine($"{field.SlangType} {field.Name};");
            }
        }
        w.WriteLine();
    }

    // ─── 工具方法 ────────────────────────────────────────────

    private static string GetSlangResourceType(FieldInfo field)
    {
        var elemType = field.GenericArgument ?? "float";
        var slangElem = MapCSharpTypeToSlang(elemType);

        return field.Kind switch
        {
            ResourceKind.ReadWriteBuffer => $"RWStructuredBuffer<{slangElem}>",
            ResourceKind.ReadOnlyBuffer => $"StructuredBuffer<{slangElem}>",
            ResourceKind.ConstantBuffer => $"ConstantBuffer<{slangElem}>",
            ResourceKind.Texture2D => $"Texture2D<{slangElem}>",
            ResourceKind.SamplerState => "SamplerState",
            ResourceKind.Scalar => GetSlangScalarType(field.TypeName),
            _ => field.TypeName,
        };
    }

    private static string GetSlangScalarType(string csharpType)
    {
        return csharpType switch
        {
            "float" or "System.Single" => "float",
            "double" or "System.Double" => "double",
            "int" or "System.Int32" => "int",
            "uint" or "System.UInt32" => "uint",
            "bool" or "System.Boolean" => "bool",
            "float2" or "MetalRenderingEngine.Shader.float2" => "float2",
            "float3" or "MetalRenderingEngine.Shader.float3" => "float3",
            "float4" or "MetalRenderingEngine.Shader.float4" => "float4",
            "int2" or "MetalRenderingEngine.Shader.int2" => "int2",
            "int3" or "MetalRenderingEngine.Shader.int3" => "int3",
            "int4" or "MetalRenderingEngine.Shader.int4" => "int4",
            "uint3" or "MetalRenderingEngine.Shader.uint3" => "uint3",
            "float4x4" or "MetalRenderingEngine.Shader.float4x4" => "float4x4",
            "Matrix4x4" or "System.Numerics.Matrix4x4" => "float4x4",
            _ => csharpType,
        };
    }

    private static string MapCSharpTypeToSlang(string typeName)
    {
        return typeName switch
        {
            "float" or "System.Single" => "float",
            "double" or "System.Double" => "double",
            "int" or "System.Int32" => "int",
            "uint" or "System.UInt32" => "uint",
            "bool" or "System.Boolean" => "bool",
            "float2" or "MetalRenderingEngine.Shader.float2" => "float2",
            "float3" or "MetalRenderingEngine.Shader.float3" => "float3",
            "float4" or "MetalRenderingEngine.Shader.float4" => "float4",
            _ => typeName,
        };
    }

    /// <summary>从全限定类型名中提取简单名（去掉命名空间前缀）。</summary>
    private static string GetSimpleTypeName(string fullTypeName)
    {
        if (string.IsNullOrEmpty(fullTypeName)) return fullTypeName;
        var lastDot = fullTypeName.LastIndexOf('.');
        return lastDot >= 0 ? fullTypeName.Substring(lastDot + 1) : fullTypeName;
    }

    /// <summary>
    /// 从类型全名中提取简单名称（如 "MetalRenderingEngine.Shader.ThreadId" → "id"）。
    /// 用于参数命名。
    /// </summary>
    private static string ExtractSimpleName(string fullTypeName)
    {
        // ThreadId → id
        if (fullTypeName.Contains("ThreadId"))
            return "id";
        // 其他类型用最后一个片段小写首字母
        var last = fullTypeName.Contains('.')
            ? fullTypeName.Substring(fullTypeName.LastIndexOf('.') + 1)
            : fullTypeName;
        if (last.Length > 0)
        {
            var first = char.ToLowerInvariant(last[0]);
            return first + last.Substring(1);
        }
        return "param";
    }

    /// <summary>获取 ThreadId 参数映射（给 StatementTranslator 用）。</summary>
    private static Dictionary<string, string> GetThreadIdMappings(ShaderInfo info)
    {
        if (info.ExecuteParameters.Count == 0)
            return new Dictionary<string, string>();

        var paramType = info.ExecuteParameters[0];
        if (!paramType.Contains("ThreadId"))
            return new Dictionary<string, string>();

        // 使用实际的参数名
        var paramName = info.ExecuteParameterNames.Count > 0
            ? info.ExecuteParameterNames[0]
            : ExtractSimpleName(paramType);

        return new Dictionary<string, string>
        {
            [paramName] = paramName,
        };
    }

    /// <summary>翻译方法体，捕获 TranslationException 转为诊断。</summary>
    private static string TryTranslateBody(string bodySource, StatementTranslator translator, List<Diagnostic> diagList)
    {
        if (string.IsNullOrWhiteSpace(bodySource))
            return "{}";

        try
        {
            // bodySource 包含完整的 C# 方法体代码，如 "{ return x * 2; }"
            // 包装为完整方法以便 Roslyn 解析
            var wrapper = $"class Wrapper {{ void _() {bodySource} }}";
            var tree = Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(wrapper);
            var methodDecl = tree.GetRoot()
                .DescendantNodes()
                .FirstOrDefault(n => n is Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax)
                as Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax;

            if (methodDecl?.Body is not null)
            {
                return translator.TranslateBlock(methodDecl.Body);
            }

            return bodySource;
        }
        catch (TranslationException tex)
        {
            if (tex.SourceLocation is not null)
            {
                diagList.Add(Diagnostic.Create(
                    Diagnostics.ShaderDiagnostics.UnsupportedExpression,
                    tex.SourceLocation,
                    tex.Message));
            }
            return $"/* Translation error: {tex.Message} */ {{}}";
        }
    }
}
